# Generated by Django 3.2.4 on 2021-06-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=80)),
                ('user_ip', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('content', models.CharField(blank=True, default=None, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
    ]
