FROM jmnote/sentinews:base

COPY . /app
WORKDIR /app
RUN  set -xe \
&& npm install --global yarn \
&& cd /app/frontend/ \
&& yarn install \
&& cd /app/backend/ \
&& pip install --no-cache-dir -r requirements.txt \
&& cd /root/ \
&& python -m textblob.download_corpora \
&& echo done...

